services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    env_file:
      - .env.example # Usar .env si existe localmente
    environment:
      - ENVIRONMENT=development
      - PORT=8080
